### ISSUE TITLE
WTC 15-A issue

### ISSUE THREAD

**Issue by Dollargrin** [J0EK3R/ebusd-configuration-weishaupt#1]
Hello

I got a Weishaupt WTC 15-A heater, an eBus Koppler USB from Esera and a raspberrypi running ebusd 3.0pre.bbc4d04. The hardware seems to be working and I was hoping your configuration files would work with my setup. A “ebusctl scan result” gives me

08;Kromschroeder;W ;0306;0301
f6;Kromschroeder;WWST?;0306;0301

and an "ebusctl find -v" gives lines similar to "hc3 HeatingDemand = no data stored" but also this line:

sc Act = Status1=1;Operatingphase=BrennerInBetrieb;Ukn2_1=1;Ukn2_2=1;Ukn2_3=1;Flame=1;GasValve1=1;GasValve2=1;Pump=1;Error=0;Ukn3_1=0;SoWi=Winter;Ukn3_3=0;Ukn3_4=0;Ukn3_5=0;Ukn3_6=0;Ukn3_7=1;SettingUV=Heating;Load=56;SupplyTemp=35.0;FlueGasTemp=-;DHWTemp=53.0;UknTemp=0.0;ExternalTemp=11;TrendTemp=14.707;SupplySetTemp=8

For example ExternalTemp and DHWTemp seem to be working here but not others, e.g. Flame which is always true. 

I'm new to this so I might have missed something basic here. Can you point me in the right direction to get more data out of my heater?

**Comment by J0EK3R** [comment]
Hello!

Sorry for this late answear, I have no time...!

I would forward you to a german forum where this topic is discussed. Perhaps you will find some more infos.
https://forum.fhem.de/index.php/topic,61017.0.html
